# Generated by Django 5.1.2 on 2024-11-10 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
        ('tipoinformacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={},
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='tipocontacto',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombres',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipoinformacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoinformacion.tipoinformacion'),
        ),
        migrations.AlterModelTable(
            name='contacto',
            table=None,
        ),
    ]
