# Generated by Django 5.1.2 on 2024-11-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_alter_contacto_options_remove_contacto_tipocontacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='hora',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
