# Generated by Django 5.1.2 on 2024-10-28 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("document_number", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("DELETED", "Eliminado"),
                        ],
                        default="ACTIVO",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="PostModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("VALIDADO", "Validado"),
                            ("DELETED", "Eliminado"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="blog.customermodel",
                    ),
                ),
                (
                    "holding",
                    models.ForeignKey(
                        db_column="holding_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holding",
                        to="publication.holdingmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post del Blog",
                "verbose_name_plural": "Posts del Blog",
                "db_table": "posts",
            },
        ),
    ]
