# Generated by Django 5.1.2 on 2024-10-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="rolemodel",
            table="roles",
        ),
    ]
