# Generated by Django 5.1.2 on 2024-10-27 23:27

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="HoldingModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=100)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("price", models.FloatField()),
                ("bedr", models.IntegerField()),
                ("bath", models.IntegerField()),
                ("park", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("INACTIVE", "Inactivo"),
                            ("DELETED", "Eliminado"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="publication.categorymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propiedad",
                "verbose_name_plural": "Propiedades",
                "db_table": "holdings",
            },
        ),
        migrations.CreateModel(
            name="UpdateHoldingLogModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("field", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "holding",
                    models.ForeignKey(
                        db_column="holding_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_holding_logs",
                        to="publication.holdingmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_user_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de actualizacion",
                "verbose_name_plural": "Logs de actualizacion",
                "db_table": "update_holding_logs",
            },
        ),
    ]
