# Generated by Django 5.1.2 on 2024-11-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nDormitorios', models.PositiveIntegerField(verbose_name='Número de Dormitorios')),
                ('nSSHH', models.PositiveIntegerField(verbose_name='Número de SSHH')),
                ('nCocheras', models.PositiveIntegerField(verbose_name='Número de Cocheras')),
                ('direccion', models.CharField(max_length=300)),
                ('archivo_imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Propiedades2',
                'verbose_name_plural': 'Propiedades2',
                'db_table': 'propiedades2',
            },
        ),
    ]
