# Generated by Django 5.1.2 on 2024-11-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_rename_archivo_imagen_propiedad_archivoimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.CharField(max_length=500),
        ),
    ]
